config/routes.rb
Demoapp::Application.routes.draw do

  devise_for :users
 resources :users   

  get "welcome/index"

  resources :quinielas
  resources :matches
  resources :compare
  match 'signup' => 'users#new', :as => :signup
  match 'matches' => 'matches#show_matches', :as => :matches
  match 'quinielas/showro/:id' => 'quinielas#showro', :as => :showro
  match 'compare/compare_by_bet/:id' => 'compare#compare_by_bet', :as => :compare_by_bet

  match 'quinielas/:id/delete' => 'quinielas#delete', :as => :delete
  
  match 'results' => 'results#show_results', :as => :results
  match 'ranking' => 'ranking#show_ranking', :as => :ranking
  match 'roundOf16' => 'ranking#show_ranking2', :as => :roundOf16
  match 'firstRound' => 'ranking#show_ranking3', :as => :firstRound
  match 'update' => 'users#edit_info', :as => :update
  match 'edit_matches' => 'matches#edit', :as => :edit_matches 
  match 'brackets' => 'quinielas#brackets', :as => :brackets 
  match 'edit' => 'users#edit', :as => :edit 
  match 'showcount' => 'users#show_count', :as => :showcount
  match 'sudocool' => 'users#sudocool'
  
  root :to => 'welcome#index'
  

end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :round
	belongs_to :team1, :class_name => "Team"
	belongs_to :team2, :class_name => "Team"
	
  attr_accessible :match_date, :team1_id, :team2_id, :round_id,:score_t1,:score_t2,:played,:winner_id, :winner_name, :editable, :match_parent1_id, :match_parent2_id
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	def new
	end

	def edit
		@matches = Match.where(round_id: 1).order("id ASC")
		@matches_round_oct = Match.where(round_id: 2).order("id ASC")
		@matches_round_cua = Match.where(round_id: 3).order("id ASC")
	    @matches_round_sem = Match.where(round_id: 4).order("id ASC")
		@matches_round_3er = Match.where(round_id: 5).order("id ASC")
		@matches_round_fin = Match.where(round_id: 6).order("id ASC")
	  	@allTeams = Team.where(status: 0).order("name asc")
	  	@session = current_user
	end

	def update
	  	@match = Match.find(params[:id])
	  	if params[:match]['score_t1'].blank? or  !params[:match]['score_t1'].numeric?
			@team1_score_int = -1
		else
			@team1_score_int = Integer(params[:match]['score_t1'])
	  	end

	  	if params[:match]['score_t2'].blank? or  !params[:match]['score_t2'].numeric?
			@team2_score_int = -1
		else
			@team2_score_int = Integer(params[:match]['score_t2'])
	  	end

	  		@winner_id = params[:match]['winner_id']
	  		
	  		if @winner_id.nil?
	  			@updated = @match.update_attributes(:team1_id=>params[:match]['team1_id'],:team2_id=>params[:match]['team2_id'])	
	  		else
	  			@updated = @match.update_attributes(:team1_id=>params[:match]['team1_id'],:team2_id=>params[:match]['team2_id'],:winner_id=>@winner_id)
	  		end
	  		if @updated
	  			if @team1_score_int > @team2_score_int
	  				@match.update_attributes(:score_t1 => @team1_score_int,:score_t2 => @team2_score_int,:winner_id => @match.team1.id,:winner_name => @match.team1.name,:played => 1)
	  			end

				if @team2_score_int > @team1_score_int
	  				@match.update_attributes(:score_t1 => @team1_score_int,:score_t2 => @team2_score_int,:winner_id => @match.team2.id,:winner_name => @match.team2.name,:played => 1)
	  			end

	  			if @team1_score_int >= 0 and  @team2_score_int >= 0 and  @team1_score_int == @team2_score_int
	  				@match.update_attributes(:score_t1 => @team1_score_int,:score_t2 => @team2_score_int,:played => 1)
	  			end

	    		redirect_to "/edit_matches##{@match.id}"
	 		else
	    		render 'edit'
	    	end
	   	end

	def show_matches
			@matches = Match.where('').order("id ASC")
			@session = current_user
			@active_matches = 'active'
			if !@session
  				redirect_to "/"
  			end
	end
end
class String
   def numeric?
    !(self =~ /^-?\d+(\.\d*)?$/).nil?
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_edit_matches.html.erb
              <div class="container">

<div class="bs-docs-section">

        <div class="row">
          <div class="col-sm-12 col-lg-12">
 
 <div class="page-header">
              <h1 id="tables"><%=title%></h1>
            </div>
               <%
               if !matches.nil?
                @var1 =  ''
                matches.each do |match| %>
                <% 
              
                if match.match_date.strftime("%m/%d") != @var1 %>
<div class="col-sm-12 col-lg-12">
                <h4>Fecha: <%= match.match_date.to_formatted_s(:short) %></h4>
                 </div>
               <% end 
                    @var1 = match.match_date.strftime("%m/%d")

                 %> 
         <%= form_for match, url: match_path(match), method: :put do |f| %>
         <div class="col-sm-8 col-lg-8">
 <table id="<%= match.id %>" class="table table-striped table-hover">
              <tbody>
              
                <tr>
                  <td><span class="flagsp flagsp_<%= match.team1.code %>" title=""> </span></td>
                  <td class="col-ajust"><% 
                    teams = @allTeams
                    

                    if match.editable == 1%>
                     <% if match.round.id > 1 %>
                    <input type="radio" name="match_<%=match.id%>" class="hidden-radio" onclick="setWinnerId(this,'<%=match.team1.id%>','<%=match.id%>')"/>
                     <% end %>
                     <%= match.team1.name %><%= f.select(:team1_id, teams.map { |value| [ value.name, value.id ] },{},:class => "form-control") %>
                    <%else%>
                    <%= match.team1.name %>
                    <%= f.hidden_field :team1_id, :value => match.team1.id %>

                    <%end%>
                    
                  </td>
                  <td class="centered" style="width: 138px;">
                    
                    <%= f.text_field   :score_t1, :class => "form-control small-control", :onkeyup => "checkForDraw(this)", :match_id => match.id%>
                    <% if match.round.id > 1 %>
                    <%= f.hidden_field :winner_id, :class => "form-control small-control"%>
                    <% end %>
                    <div class="form-separator">-</div>
                    <%= f.text_field :score_t2, :class => "form-control small-control", :onkeyup => "checkForDraw(this)", :match_id => match.id %>
                    
                  </td>
                  <td class="rigth-align col-ajust">
                                        <% 
                  
                    
                    if match.editable == 1 %>
                     <%= match.team2.name %>
                     <% if match.round.id > 1 %>
                    <input type="radio" name="match_<%=match.id%>" class="hidden-radio" onclick="setWinnerId(this,'<%=match.team2.id%>','<%=match.id%>')"/>
                    <% end %>
                      <%= f.select(:team2_id, teams.map { |value| [ value.name, value.id ] },{}, :class => "form-control") %>

                    <%else%>
                    <%= match.team2.name %>
                    <%= f.hidden_field :team2_id, :value => match.team2.id %>
                    <%end%>
                  </td>
                   <td class="rigth-align"> <span class="flagsp flagsp_<%= match.team2.code %>" title=""> </span></td>
                  
                </tr> 

              </tbody>
            </table>
         </div>
         <div class="col-sm-4 col-lg-4">
 <%= f.submit "ACTUALIZAR", :class => "btn btn-success" %>
         </div>
         
              <% end %>


              <% end 
            end%>
                          </div></div></div></div>

app/views/matches/_group.html.erb
<h3><%= group %></h3>
            <table class="table table-striped table-hover ">
              <tbody><tr>
                  <th>#</th>
                  <th>Equipo</th>
                
                </tr>
                
               <% teams.each do |team| %>
                <tr>
                  <td><span class="flagsp flagsp_<%= team.code %>" title="<%= team.name %>"> </span></td>
                  <td><%= team.name %></td>
                </tr> 
              <% end %>

              </tbody>
            </table>

app/views/matches/_matches.html.erb
 <div class="page-header">
              <h1 id="tables">Fase de grupos</h1>
            </div>
            
              
               <%
                @var1 =  ''
                @matches.each do |match| %>
             
                <% 
              
                if match.match_date.strftime("%m/%d") != @var1 %>

                <h4>Fecha: <%= match.match_date.to_formatted_s(:short) %></h4>
                 
               <% end 
                    @var1 = match.match_date.strftime("%m/%d")
                 %> 

<table class="table table-striped table-hover">
              <tbody>
              
                <tr>
                  <td><span class="flagsp flagsp_<%= match.team1.code %>" title=""> </span></td>
                  <td class="col-ajust"><%= match.team1.name %></td>
                  <td class="centered"><%= match.match_date.to_formatted_s(:time) %></td>
                  <td class="rigth-align col-ajust"><%= match.team2.name %></td>
                   <td class="rigth-align"> <span class="flagsp flagsp_<%= match.team2.code %>" title=""> </span></td>
                  
                </tr> 

              </tbody>
            </table>
              <% end %>

app/views/matches/edit.html.erb
<div class="separator-top"></div>
<%= render :partial => 'edit_matches', :locals => {:matches => @matches, :title => 'Editar Fase de grupos', :round_id => 1}  %>
<%= render :partial => 'edit_matches', :locals => {:matches => @matches_round_oct, :title => 'Editar Octavos de final', :round_id => 2} %>
<%= render :partial => 'edit_matches', :locals => {:matches => @matches_round_cua, :title => 'Editar Cuartos de final', :round_id => 3} %>
<%= render :partial => 'edit_matches', :locals => {:matches => @matches_round_sem, :title => 'Editar Semi final', :round_id => 4} %>
<%= render :partial => 'edit_matches', :locals => {:matches => @matches_round_3er, :title => 'Editar 3er Lugar', :round_id => 5} %>
<%= render :partial => 'edit_matches', :locals => {:matches => @matches_round_fin, :title => 'Editar Final', :round_id => 6} %>

app/views/matches/show_matches.html.erb
<div class="separator-top"></div>
<div class="container">

<div class="bs-docs-section">

        <div class="row">
          <div class="col-sm-8 col-lg-8">
           

            <%= render :partial => 'matches', :locals => { :match => @matches } %>
            
          </div>

          
        </div>
      </div>


</div>